### ISSUE TITLE
Addition of voltages to periodic logging

### ISSUE THREAD

**Issue by djkraven** [MilhouseVH/bcmstat#11]
Is it possible to add the all voltages to the periodic logline or is there a configuration setting that I have missed? I see the voltage displayed at the start and the (e) option for core voltage on the logging. Is it possible to include the other voltages status? The one voltage that may not be available would the one from the power supply connection to help determine if the supply is failing or if the Pi is having an issue.

This is a useful script for identifying and troubleshooting if there are hardware issues.

**Comment by MilhouseVH** [comment]
It's possible to add them, but the only other voltages are for [sdram](https://elinux.org/RPI_vcgencmd_usage) (`sdram_c`, `sdram_i`, `sdram_p`) and to be honest I'm not sure these values are that interesting, are they?

**Comment by djkraven** [comment]
The values that would be most helpful but I don't think are available from the Pi are the voltage and amperage from the power supply. I see the yellow lightning bolt when on a local monitor but have not found a way to log that and see the detail behind it.

I agree the sdram voltages probably don't have much value beyond curiosity though in the rare instances of them failing it could be helpful.

**Comment by MilhouseVH** [comment]
The voltage and amps from the PSU are not available.

On systems where it is supported (ie. RPi3, RPi3+ etc.) you can see when an under voltage (U), frequency cap (F) or temperature throttle (T) event has occurred when using the script with the `y` option - this will enable the `UFT` column. When exiting the script, you will also see a total for the number of U/F/T events.

I'm going to close this issue as I don't think there's much more that can be added.
