### ISSUE TITLE
SUGGESTION: Specify each field

### ISSUE THREAD

**Issue by vegerot** [MilhouseVH/bcmstat#17]
When I run bcmstat in a smaller Tmux pane I'll get some ugly wrapping which makes the output hard to read.  I know some fields are optional, but it seems like most of them are not.   How can I only allow a few select fields?

**Comment by MilhouseVH** [comment]
This script really isn't suitable for narrow consoles, I'm afraid. I suppose you could always try piping the output through some sort of filter script that formats the output to fit your Tmux pane.

**Comment by MilhouseVH** [comment]
I've added the `-o` option in v.0.5.5 that allows columns to be configured. Column names are case sensitive. The order of columns can't be specified, only which columns are visible.

Some examples:

Hide H264, show V3D:
```
-o-H264,+V3D
```
Hide all CPU load stats other than `total`:
```
-x -o-CPUuser,-CPUnice,-CPUsys,-CPUidle,-CPUiowt,-CPUirq,-CPUs/irq
```
Show only ARM frequency, Core frequency, and Core temp:
```
-oARM,Core,TempCore
```

Columns will only be displayed if they are active, so for example `-oCPU` won't display CPU processor stats (`cpu0`, `cpu1`, `cpu2`, `cpu3` etc.) unless `-p` is also specified (as `-p` activates monitoring of CPU cores).

See `-h` for available column names.

**Comment by vegerot** [comment]
Awesome
