### ISSUE TITLE
Use v3d instead of h264 for GPU frequencies

### ISSUE THREAD

**Issue by jfikar** [MilhouseVH/bcmstat#19]
It seems that on Raspberry Pi 4 `vcgencmd measure_clock h264` always returns 0. Maybe it would be useful to monitor the GPU frequencies by `vcgencmd measure_clock v3d`?

**Comment by MilhouseVH** [comment]
I guess that might be true only if you never use video decode that enables the H264 block?

I'll have a think about adding an option to monitor an alternative block.

**Comment by jfikar** [comment]
You are right, H264 is unused as I use it without display. On the other hand, next to Raspberry Pi 4 I also have one Raspberry Pi 3B+ (without display too) and here H264 frequency is shown (300 MHz by default).

I'll try to run a test with an H264 video.

**Comment by MilhouseVH** [comment]
Closing as fixed in v0.5.5.

See https://github.com/MilhouseVH/bcmstat/issues/17#issuecomment-628913770 for details.
