### ISSUE TITLE
Not support Pi zero w

### ISSUE THREAD

**Issue by iciness** [MilhouseVH/bcmstat#7]
./bcmstat.sh
  Config: v0.4.4, args "", priority lowest (+19)
   Board: 1 x ARMv6 core available, ondemand governor (Pi1 Unknown rev 1.1, BCM2835 SoC with 512MB RAM by Sony)
  Memory: 512MB (split 448MB ARM, 64MB GPU) plus 100MB Swap
HW Block: |   ARM   |  Core  |  H264  |    SDRAM    |
Min Freq: |  700MHz | 250MHz |   0MHz |    450MHz   |
Max Freq: | 1000MHz | 400MHz | 300MHz |    450MHz   |
Voltages: |         0, 1.3500V        | +1, 1.2250V |
   Other: temp_limit=85, disable_auto_turbo=1
Firmware: Apr 27 2017 17:19:34, version 17af5814bb19dbb7c70ccd2c845b80a160943811 (clean) (release)
  Codecs: H264 H263 MPG4 MJPG PCM
  Booted: Fri Apr 28 13:02:58 2017

Error: Network interface eth0 is not valid!

**Comment by MilhouseVH** [comment]
Use `./bcmstat.sh -iwlan0`?

I'll make eth0 non-fatal in a future release.

**Comment by iciness** [comment]
ok

**Comment by Swap-File** [comment]
I get eth0 errors on Raspbian Stretch too, it sounds like Stretch uses a different network device naming scheme? 

https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/

**Comment by MilhouseVH** [comment]
@Swap-File So what is eth0 now called in Stretch?

Unless it's got a fixed name (which I might support as an alternative to eth0) you can just use `-i<whatever-eth0-is-now-called>`.

**Comment by Swap-File** [comment]
By default it's named "enx[MAC ADDRESS]", so it will be different on everyone's installation.  

It might be useful to put a reminder in the "Network interface eth0 is not valid!" error message to tell users to look at ifconfig for their network interface name and specify it themselves if they are running Stretch.   

I'm not sure what the best way would be to automatically detect the interface name.  And I guess reverting back to the old style naming breaks things in Raspbian, but I have not tried it.

**Comment by MilhouseVH** [comment]
Can you attach the contents of your `/proc/net/dev`.

**Comment by Swap-File** [comment]
This is from my Pi3 running Raspbian Stretch Lite:

[dev.txt](https://github.com/MilhouseVH/bcmstat/files/1258110/dev.txt)

**Comment by MilhouseVH** [comment]
Thanks. Can you try the latest version 0.4.5? It should fix all the issues listed here - if it can't determine the default interface (`eth0` or `enxb827eb*`) then it will default to `wlan0` which should help Pi0W users.

For anyone else that needs to use a different interface they'll need to specify it as before eg. `-ibr1` etc., either on the command line or added to `~/.bcmstat.conf`.

An invalid interface will now fail silently, with no network stats output.

**Comment by Swap-File** [comment]
Thanks!  It seems to work perfectly here.
