### ISSUE TITLE
Update for Pi0 W rev.1.1

### ISSUE THREAD

**Issue by olober** [MilhouseVH/bcmstat#8]
FYI: I just tested latest bcmstat and for Pi0 W it shows _Pi1 Unknown rev. 1.1_ so I made a small patch (one print) and discovered that pcb_base is 0x9000C1. So I patched for me _self.models_ and _self.pcbs_ but I don't how submit it here, etc... so I just want to send this info here.
Thanks for the script.

**Comment by MilhouseVH** [comment]
Thanks. 628b396b38432c1dd8a6643a1aa22b3ff713394b should fix this.
