### ISSUE TITLE
File extension of bcmstat.sh

### ISSUE THREAD

**Issue by niemandag** [MilhouseVH/bcmstat#9]
The file bcmstat.sh has the extension .sh, which would make it a shell script. But it isn't a shell script, it is a python script.
I know that's not how extensions work in linux, but it would be nice to see what program it actually needs without having to open the file and look at the first line.
I have tried to run this with `sh bcmstat.sh` so many times.

**Comment by MilhouseVH** [comment]
Yes I know it's not ideal, but it started life as a bash shell script, and a year or two later I rewrote it in Python (which is also about the time when I put it on Github). However by that time the name with `.sh` extension had already become (somewhat) established (forum posts, links etc.) so I was stuck with it.

Feel free to rename the script to whatever name you prefer, it will still work (and update itself).

**Comment by niemandag** [comment]
Ok, that makes sense. I will do so. Thanks.
